export const top1 = require('@/assets/image/icon/top1.png')
export const top2 = require('@/assets/image/icon/top2.png')
export const top3 = require('@/assets/image/icon/top3.png')
export const pad = require('@/assets/image/icon/pad.png')
export const camera = require('@/assets/image/icon/camera.png')
export const blue = require('@/assets/image/icon/blue.png')
export const red = require('@/assets/image/icon/red.png')
export const green = require('@/assets/image/icon/green.png')
